---

### Generic smell configuration

detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    exclude:
      - "MyWorker#self.class_method" # should be refactored
      - "AnotherWorker#instance_method" # should be refactored as well

  RepeatedConditional:
    max_ifs: 4

### Directory specific configuration

directories:
  "web_app/app/controllers":
    NestedIterators:
      enabled: false
  "web_app/app/helpers":
    UtilityFunction:
      enabled: false

### Excluding directories

exclude_paths:
  - lib/legacy
  - lib/rake/legacy_tasks
  - lib/smelly.rb
